PrimeFacesOnSpringBoot/src/main/java/de/beyondjava/examples/scopes/jsf/HelloWorldBean.java
/**
 *  (C) 2013-2014 Stephan Rauh http://www.beyondjava.net
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package de.beyondjava.examples.scopes.jsf;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

@ManagedBean
@ViewScoped
public class HelloWorldBean {
	public String getHello() {
		return "Hello from PrimeFaces and Spring Boot!";
	}
}

PrimeFacesOnSpringBoot/src/main/webapp/index.xhtml
<f:view xmlns="http://www.w3c.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:ng="http://xmlns.jcp.org/jsf/passthrough"
	xmlns:prime="http://primefaces.org/ui">
	<h:head>
		<meta charset="utf-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
		<title>#{menuController.title}</title>
		<style>
		body {font-size:12px; }
</style>
	</h:head>
	<h:body>
		<h:form>
			<prime:panel header="What do you see here?" >
				<div style="height:50px">
					This is a simple PrimeFaces 5 project running on Spring Boot 1.1.4.
				</div>
			</prime:panel>
			<prime:panel header="JSF 2.2 Bean Access">
				#{helloWorldBean.hello}
			</prime:panel>
		</h:form>
	</h:body>
</f:view>